version: "3.9"
services:
  pen:
    build: .
    ports:
      - "57575:57575"
  semantic:
    image: "docker.pkg.github.com/github/semantic/semantic:latest"
    restart: always
  duckling:
    image: rasa/duckling:0.1.6.5
    restart: always
    ports:
      - 8000:8000